default:
    adapter: mysql2
    database:  xxxxxxxxxxxxxxxxx
    username: admin25
    password: w0rk5pac3
    host: localhost
development:
    adapter: mysql2
    database: xxxxxxxxxxxxxxxxx
    username: admin25
    password: w0rk5pac3
    host: localhost
production:
    adapter: mysql2
    database:  xxxxxxxxxxxxxxxxx
    username: admin25
    password: w0rk5pac3
    host: localhost